---
- hosts: all
  become: true
  tasks:
    - name: install httpd pkg
      pkg:
        name: httpd
        state: latest
    - name: write apache config file
      template:
          src: /srv/httpd.j2
          dest:  /etc/httpd.conf
